import { useAuth } from "@/_core/hooks/useAuth";
import { AirfoilCanvas } from "@/components/AirfoilCanvas";
import { PageHero, PageShell } from "@/components/PageShell";
import { trpc } from "@/lib/trpc";
import { CHALLENGES, formatReynolds, getChallenge, solveFlow, SOLVER_LIMITS, type SolverInput } from "@shared/aeroforge";
import { getPlan, planAllows } from "@shared/plans";
import { Activity, ArrowRight, BookOpenCheck, CheckCircle2, ChevronRight, CircleGauge, CloudCog, FlaskConical, Gauge, Info, Layers3, LockKeyhole, Play, Save, ShieldCheck, SlidersHorizontal, Sparkles, Target, Wind } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

const stageLabels = ["Brief", "Geometry", "Conditions", "Solve", "Contours", "Review", "Save", "Artifact"];

export default function AeroForgePage() {
  const [, setLocation] = useLocation();
  const { user, isAuthenticated } = useAuth();
  const [input, setInput] = useState<SolverInput>({ challengeId: "transonic-airfoil", mach: 0.62, alphaDeg: 4, altitudeKm: 5 });
  const [label, setLabel] = useState("");
  const [activeStage, setActiveStage] = useState(0);
  const [hasRun, setHasRun] = useState(false);
  const result = useMemo(() => solveFlow(input), [input]);
  const challenge = getChallenge(input.challengeId);
  const plan = getPlan(user?.planId);
  const canSave = isAuthenticated && planAllows(user?.planId, "saveTrial");
  const trials = trpc.aeroforge.list.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const utils = trpc.useUtils();
  const saveTrial = trpc.aeroforge.save.useMutation({
    onSuccess: () => {
      toast.success("AeroForge trial saved", { description: "The run is now available in your student workspace." });
      setLabel("");
      utils.aeroforge.list.invalidate();
      setActiveStage(6);
    },
    onError: error => toast.error("Could not save trial", { description: error.message }),
  });

  const change = <K extends keyof SolverInput>(key: K, value: SolverInput[K]) => setInput(current => ({ ...current, [key]: value }));
  const execute = () => { setHasRun(true); setActiveStage(3); toast.success("Analytical flow solver executed", { description: `${challenge.solver} · ${result.regime}` }); };
  const save = () => {
    if (!isAuthenticated) { setLocation("/auth?next=/aeroforge"); return; }
    if (!canSave) { setLocation("/pricing?reason=save-trial"); return; }
    saveTrial.mutate({ ...input, label: label || undefined });
  };

  return <PageShell>
    <PageHero eyebrow="AeroForge // Simulation Lab" title={<>Engineering intuition, <span className="brand-gradient-text">made inspectable.</span></>} description="Configure reduced-order aerodynamic models, observe deterministic flow contours, compare a benchmark delta, and preserve validated experiments in your Project Polaris workspace.">
      <div className="flex flex-wrap gap-3"><span className="inline-flex items-center gap-2 rounded-full border border-success/25 bg-success/8 px-3 py-2 font-mono text-[0.6rem] text-success"><span className="pulse-dot h-1.5 w-1.5 rounded-full bg-success" />Solver cluster online</span><span className="rounded-full border border-border bg-card px-3 py-2 font-mono text-[0.6rem] text-muted-foreground">Educational reduced-order model</span></div>
    </PageHero>
    <section className="container px-4 py-8 sm:px-6 sm:py-12">
      <div className="no-scrollbar -mx-1 flex gap-1 overflow-x-auto px-1 pb-1">{stageLabels.map((stage, index) => <button key={stage} onClick={() => setActiveStage(index)} type="button" className={`press shrink-0 rounded-lg px-3 py-2 font-mono text-[0.6rem] transition-colors ${activeStage === index ? "bg-primary text-primary-foreground" : "border border-border bg-card text-muted-foreground hover:border-primary/35 hover:bg-primary/8 hover:text-foreground"}`}><span className="mr-1.5 opacity-65">{String(index + 1).padStart(2, "0")}</span>{stage}</button>)}</div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[0.78fr_1.22fr]">
        <aside className="space-y-5">
          <section className="rounded-2xl border border-border bg-card p-4 sm:p-5"><p className="flex items-center gap-2 font-mono text-[0.61rem] font-semibold uppercase tracking-[0.1em] text-muted-foreground"><Target className="h-3.5 w-3.5 text-primary" />01 // Engineering challenge</p><div className="mt-4 space-y-2">{CHALLENGES.map(candidate => { const locked = candidate.requiredTier > 0 && !planAllows(user?.planId, "fullSolvers"); return <button key={candidate.id} type="button" onClick={() => { change("challengeId", candidate.id); setHasRun(false); setActiveStage(0); }} className={`press w-full rounded-xl border p-3 text-left transition-all ${candidate.id === input.challengeId ? "border-primary/60 bg-primary/10 shadow-lg shadow-primary/5" : "border-border bg-secondary/25 hover:border-primary/35 hover:bg-primary/5"}`}><span className="flex items-center justify-between gap-3"><span className="font-mono text-[0.54rem] uppercase tracking-[0.1em] text-primary">{candidate.category}</span>{locked && <span className="inline-flex items-center gap-1 font-mono text-[0.52rem] text-gold"><LockKeyhole className="h-2.5 w-2.5" />Builder+</span>}</span><span className="mt-1.5 block text-sm font-semibold leading-5 text-foreground">{candidate.name}</span><span className="mt-1 block font-mono text-[0.54rem] text-muted-foreground">NACA {candidate.naca} · {candidate.solver}</span></button>; })}</div></section>
          <section className="rounded-2xl border border-border bg-card p-4 sm:p-5"><p className="flex items-center gap-2 font-mono text-[0.61rem] font-semibold uppercase tracking-[0.1em] text-muted-foreground"><SlidersHorizontal className="h-3.5 w-3.5 text-primary" />02–03 // Conditions</p><div className="mt-5 space-y-5"><Range label="Mach Number" readout={`M ${input.mach.toFixed(2)}`} min={SOLVER_LIMITS.mach.min} max={SOLVER_LIMITS.mach.max} step={SOLVER_LIMITS.mach.step} value={input.mach} onChange={value => change("mach", value)} /><Range label="Angle of Attack" readout={`${input.alphaDeg.toFixed(1)}°`} min={SOLVER_LIMITS.alphaDeg.min} max={SOLVER_LIMITS.alphaDeg.max} step={SOLVER_LIMITS.alphaDeg.step} value={input.alphaDeg} onChange={value => change("alphaDeg", value)} tone="gold" /><Range label="Altitude" readout={`${input.altitudeKm.toFixed(1)} km`} min={SOLVER_LIMITS.altitudeKm.min} max={SOLVER_LIMITS.altitudeKm.max} step={SOLVER_LIMITS.altitudeKm.step} value={input.altitudeKm} onChange={value => change("altitudeKm", value)} tone="cyan" /></div><button type="button" onClick={execute} className="press mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[image:var(--grad-brand)] px-4 py-3 font-mono text-[0.66rem] font-semibold text-[#090710] shadow-lg shadow-primary/20"><Play className="h-3.5 w-3.5 fill-current" />Execute Analytical Flow Solver</button></section>
          <section className="rounded-2xl border border-primary/15 bg-primary/6 p-4"><div className="flex gap-2"><Info className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><div><p className="font-mono text-[0.6rem] font-semibold text-foreground">Model boundary</p><p className="mt-1 text-xs leading-5 text-muted-foreground">AeroForge is an educational reduced-order analysis: thin-airfoil, compressibility, and ISA atmosphere relations—not certification-grade CFD.</p></div></div></section>
        </aside>
        <div className="space-y-5">
          <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border bg-secondary/30 px-4 py-3 sm:px-5"><span className="inline-flex items-center gap-2 font-mono text-[0.62rem] font-medium text-foreground"><Activity className="h-3.5 w-3.5 text-success" />NACA {result.naca} Flow Field Contours</span><span className="font-mono text-[0.54rem] text-muted-foreground">Grid 120 × 80 · {challenge.solver}</span></div><div className="relative h-[295px] bg-[#100e19] sm:h-[390px]"><AirfoilCanvas challengeId={input.challengeId} mach={input.mach} alphaDeg={input.alphaDeg} />{!hasRun && <div className="absolute inset-0 flex items-center justify-center bg-[#100e19]/30"><span className="rounded-full border border-white/15 bg-black/40 px-4 py-2.5 font-mono text-[0.6rem] text-white/70">Set conditions, then execute the solver</span></div>}<div className="absolute left-3 top-3 rounded-lg border border-white/10 bg-black/35 px-2.5 py-2 font-mono text-[0.54rem] text-white/75">{challenge.name}<br /><span className="text-violet-200">M {result.mach.toFixed(2)} · α {result.alphaDeg.toFixed(1)}° · {result.altitudeKm.toFixed(1)} km</span></div></div><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4"><Metric icon={Wind} label="Lift coefficient" value={result.liftCoefficient.toFixed(4)} tone="violet" /><Metric icon={Gauge} label="Drag coefficient" value={result.dragCoefficient.toFixed(5)} tone="primary" /><Metric icon={CircleGauge} label="L/D efficiency" value={result.liftToDrag.toFixed(2)} tone="cyan" /><Metric icon={CloudCog} label="True airspeed" value={`${result.trueAirspeedKmh.toFixed(0)} km/h`} tone="gold" /></div></section>
          <section className="grid gap-4 lg:grid-cols-[1fr_0.8fr]"><div className="rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><p className="font-mono text-[0.59rem] uppercase tracking-[0.1em] text-muted-foreground">Benchmark delta</p><p className="mt-1 font-display text-3xl font-bold text-foreground"><span className={Math.abs(result.benchmarkDelta) < 15 ? "text-success" : "text-gold"}>{result.benchmarkDelta > 0 ? "+" : ""}{result.benchmarkDelta.toFixed(1)}%</span><span className="ml-2 text-base font-normal text-muted-foreground">vs reference L/D</span></p><p className="mt-2 text-xs leading-5 text-muted-foreground">{result.benchmarkSource} · Re {formatReynolds(result.reynolds)} · {result.regime}</p></div></div>{result.notes.length ? <div className="mt-4 space-y-2 border-t border-border pt-4">{result.notes.map(note => <p key={note} className="flex gap-2 text-xs leading-5 text-muted-foreground"><Sparkles className="mt-1 h-3 w-3 shrink-0 text-gold" />{note}</p>)}</div> : <p className="mt-4 border-t border-border pt-4 text-xs leading-5 text-muted-foreground">No separation or high-altitude warnings at the current conditions. Use the sliders to explore regime boundaries.</p>}</div><div className="rounded-2xl border border-primary/20 bg-[image:var(--grad-brand-soft)] p-4 sm:p-5"><p className="font-mono text-[0.59rem] uppercase tracking-[0.1em] text-primary">06–07 // Trial record</p><input value={label} onChange={event => setLabel(event.target.value)} maxLength={160} placeholder="Label this experiment (optional)" className="mt-4 h-11 w-full rounded-xl border border-border bg-card/75 px-3 text-sm text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20" /><button type="button" disabled={saveTrial.isPending} onClick={save} className="press mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-mono text-[0.65rem] font-semibold text-primary-foreground disabled:cursor-wait disabled:opacity-70"><Save className="h-3.5 w-3.5" />{saveTrial.isPending ? "Saving trial…" : canSave ? "Save Trial" : isAuthenticated ? "Upgrade to Save Trials" : "Sign in to Save"}</button><p className="mt-3 text-xs leading-5 text-muted-foreground">{canSave ? "Saved runs include all numerical inputs and output metrics." : `${plan.name} includes live solver exploration. Builder adds unlimited saved trials.`}</p></div></section>
          <section className="rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="font-mono text-[0.59rem] uppercase tracking-[0.1em] text-muted-foreground">08 // Saved trial ledger</p><h2 className="mt-1 font-display text-2xl font-bold text-foreground">Recent computational records</h2></div><Link href="/portal" className="press inline-flex items-center gap-1.5 rounded-full border border-primary/35 px-3 py-2 font-mono text-[0.58rem] text-primary hover:bg-primary hover:text-primary-foreground">Workspace <ChevronRight className="h-3 w-3" /></Link></div>{!isAuthenticated ? <div className="mt-4 rounded-xl border border-dashed border-border bg-secondary/20 p-5 text-center"><LockKeyhole className="mx-auto h-4 w-4 text-primary" /><p className="mt-2 text-sm text-foreground">Sign in to retain a simulation history.</p><Link href="/auth?next=/aeroforge" className="mt-2 inline-block font-mono text-[0.6rem] text-primary hover:text-gold">Sign in to your workspace →</Link></div> : trials.isLoading ? <p className="mt-4 font-mono text-[0.6rem] text-muted-foreground">Loading saved runs…</p> : trials.data?.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[660px] text-left"><thead><tr className="border-b border-border font-mono text-[0.52rem] uppercase tracking-[0.08em] text-muted-foreground"><th className="px-2 py-2">Trial</th><th className="px-2 py-2">Conditions</th><th className="px-2 py-2">CL / CD</th><th className="px-2 py-2">L/D</th><th className="px-2 py-2">Delta</th></tr></thead><tbody>{trials.data.map(trial => <tr key={trial.id} className="border-b border-border/70 text-xs text-muted-foreground last:border-b-0"><td className="px-2 py-3"><p className="font-medium text-foreground">{trial.label || trial.challengeName}</p><p className="mt-0.5 font-mono text-[0.52rem]">{new Date(trial.createdAt).toLocaleDateString()}</p></td><td className="px-2 py-3 font-mono text-[0.57rem]">M {trial.mach} · α {trial.alphaDeg}° · {trial.altitudeKm} km</td><td className="px-2 py-3 font-mono text-[0.57rem]">{trial.liftCoefficient} / {trial.dragCoefficient}</td><td className="px-2 py-3 font-mono text-[0.57rem] text-primary">{trial.liftToDrag}</td><td className="px-2 py-3 font-mono text-[0.57rem] text-gold">{trial.benchmarkDelta}%</td></tr>)}</tbody></table></div> : <div className="mt-4 rounded-xl border border-dashed border-border bg-secondary/20 p-5 text-center"><FlaskConical className="mx-auto h-4 w-4 text-primary" /><p className="mt-2 text-sm text-foreground">No saved trials yet.</p><p className="mt-1 text-xs text-muted-foreground">Execute a run, then save it to retain an inspectable record.</p></div>}</section>
        </div>
      </div>
      <div className="mt-6 flex flex-col gap-3 rounded-2xl border border-border bg-[var(--surface)] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><BookOpenCheck className="mt-0.5 h-5 w-5 shrink-0 text-gold" /><p className="max-w-3xl text-xs leading-6 text-muted-foreground"><span className="font-medium text-foreground">Learning note.</span> Interpret the sign and magnitude of each output before comparing any reference. Differences can come from geometry simplification, model scope, atmospheric assumptions, or an out-of-range regime.</p></div><Link href="/resources" className="press shrink-0 font-mono text-[0.6rem] text-primary hover:text-gold">Study the solver references →</Link></div>
    </section>
  </PageShell>;
}

function Range({ label, readout, min, max, step, value, onChange, tone = "violet" }: { label: string; readout: string; min: number; max: number; step: number; value: number; onChange: (value: number) => void; tone?: "violet" | "gold" | "cyan" }) {
  const text = tone === "gold" ? "text-gold" : tone === "cyan" ? "text-cyan-300" : "text-primary";
  const accent = tone === "gold" ? "accent-[#d4af37]" : tone === "cyan" ? "accent-cyan-400" : "accent-primary";
  return <label className="block"><span className="flex items-center justify-between gap-4 font-mono text-[0.59rem] text-muted-foreground"><span>{label}</span><span className={text}>{readout}</span></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))} className={`polaris-range mt-2.5 ${accent}`} /></label>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof Wind; label: string; value: string; tone: "violet" | "primary" | "cyan" | "gold" }) {
  const color = tone === "violet" ? "text-violet-300" : tone === "primary" ? "text-primary" : tone === "cyan" ? "text-cyan-300" : "text-gold";
  return <div className="bg-card px-3 py-4 sm:px-4"><Icon className={`h-3.5 w-3.5 ${color}`} /><p className="mt-3 font-mono text-[0.49rem] uppercase tracking-[0.08em] text-muted-foreground">{label}</p><p className={`mt-1 font-mono text-base font-semibold ${color}`}>{value}</p></div>;
}
